### ISSUE TITLE
Add support for Node v10

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-node#24]
The following specs fails for unknown reasons when running them with Node `v9.5.0`. I'm not sure whether this just has to do with the tests or if it is something else in the API client that doesn't work in the new Node version.

```
  1) client #execute_query with invalid api key should throw error on invalid API key:
      Uncaught AssertionError [ERR_ASSERTION]: Mocks not yet satisfied:
GET http://api.twingly.com:443/blog/search/api/v3/search?apikey=wrong&q=something
      + expected - actual
      -false
      +true
      
      at Object.done (node_modules/nock/lib/scope.js:244:12)
      at Cassette.eject (node_modules/nock-vcr/lib/nock-vcr.js:140:29)
      at Object.ejectCassette (node_modules/nock-vcr/lib/nock-vcr.js:171:58)
      at test/test_client.js:70:26
      at lib/parser.js:24:13
      at Parser.<anonymous> (node_modules/xml2js/lib/parser.js:303:18)
      at SAXParser.onclosetag (node_modules/xml2js/lib/parser.js:261:26)
      at emit (node_modules/sax/lib/sax.js:624:35)
      at emitNode (node_modules/sax/lib/sax.js:629:5)
      at closeTag (node_modules/sax/lib/sax.js:889:7)
      at SAXParser.write (node_modules/sax/lib/sax.js:1436:13)
      at Parser.exports.Parser.Parser.parseString (node_modules/xml2js/lib/parser.js:322:31)
      at Parser.parseString (node_modules/xml2js/lib/parser.js:5:59)
      at exports.parseString (node_modules/xml2js/lib/parser.js:354:19)
      at Parser.parse (lib/parser.js:20:5)
      at lib/client.js:67:24
      at IncomingMessage.<anonymous> (lib/client.js:113:17)
      at endReadableNT (_stream_readable.js:1101:12)
      at process._tickCallback (internal/process/next_tick.js:152:19)
  2) query #execute() when searching for spotify should get posts:
      Uncaught AssertionError [ERR_ASSERTION]: Mocks not yet satisfied:
GET http://api.twingly.com:443/blog/search/api/v3/search?apikey=test-key&q=spotify%20page-size%3A10%20lang%3Asv
      + expected - actual
      -false
      +true
      
      at Object.done (node_modules/nock/lib/scope.js:244:12)
      at Cassette.eject (node_modules/nock-vcr/lib/nock-vcr.js:140:29)
      at Object.ejectCassette (node_modules/nock-vcr/lib/nock-vcr.js:171:58)
      at test/test_query.js:126:26
      at lib/parser.js:24:13
      at Parser.<anonymous> (node_modules/xml2js/lib/parser.js:303:18)
      at SAXParser.onclosetag (node_modules/xml2js/lib/parser.js:261:26)
      at emit (node_modules/sax/lib/sax.js:624:35)
      at emitNode (node_modules/sax/lib/sax.js:629:5)
      at closeTag (node_modules/sax/lib/sax.js:889:7)
      at SAXParser.write (node_modules/sax/lib/sax.js:1436:13)
      at Parser.exports.Parser.Parser.parseString (node_modules/xml2js/lib/parser.js:322:31)
      at Parser.parseString (node_modules/xml2js/lib/parser.js:5:59)
      at exports.parseString (node_modules/xml2js/lib/parser.js:354:19)
      at Parser.parse (lib/parser.js:20:5)
      at lib/client.js:67:24
      at IncomingMessage.<anonymous> (lib/client.js:113:17)
      at endReadableNT (_stream_readable.js:1101:12)
      at process._tickCallback (internal/process/next_tick.js:152:19)
```

(This was discovered in #23)

**Comment by dentarg** [comment]
We could do https://github.com/twingly/twingly-search-api-node/issues/17 and see if this is still an issue :)

**Comment by roback** [comment]
Running the tests with Node v8.9.4 records fixtures correctly, but running with v9.5.0 does not record anything.

    NOCK_VCR_MODE=ALL npm test

`NOCK_VCR_MODE=ALL` - always record new fixtures, see [nock-vcr README](https://github.com/carbonfive/nock-vcr#usage)

### Fixture after running with Node v8.9.4

```js
// File: test/cassettes/search_without_valid_api_key.js

module.exports = exports = function(nock) {
var refs = [];

refs[0] = nock('http://api.twingly.com:443')
  .get('/blog/search/api/v3/search?apikey=wrong&q=something')
  .reply(401, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error code=\"40101\"><message>Unauthorized</message></error>", { server: 'nginx',
  date: 'Thu, 15 Feb 2018 15:23:25 GMT',
  'content-type': 'application/xml; charset=utf-8',
  'content-length': '97',
  connection: 'close',
  'cache-control': 'no-cache',
  pragma: 'no-cache',
  expires: '-1' });


return refs;
};
```

### Fixture after running with Node v9.5.0

```js
// File: test/cassettes/search_without_valid_api_key.js

module.exports = exports = function(nock) {
var refs = [];


return refs;
};
```

It looks like there's some changes in the new node version that's not compatible with `nock-vcr`.

**Comment by roback** [comment]
I also discovered that you can make the tests pass on 9.5.0 by manually editing `http` to `https` in the already recorded fixtures...

**Comment by roback** [comment]
Updated the title since Node v9 is EOL since 2018-06-30. The current release is v10.

Source: https://github.com/nodejs/Release
